// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: labyrinth.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Labyrinth_GetLabyrinthInfo_FullMethodName = "/labyrinth.Labyrinth/GetLabyrinthInfo"
	Labyrinth_GetPlayerStatus_FullMethodName  = "/labyrinth.Labyrinth/GetPlayerStatus"
	Labyrinth_RegisterMove_FullMethodName     = "/labyrinth.Labyrinth/RegisterMove"
	Labyrinth_Revelio_FullMethodName          = "/labyrinth.Labyrinth/Revelio"
	Labyrinth_Bombarda_FullMethodName         = "/labyrinth.Labyrinth/Bombarda"
)

// LabyrinthClient is the client API for Labyrinth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabyrinthClient interface {
	GetLabyrinthInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LabyrinthInfo, error)
	GetPlayerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayerStatus, error)
	RegisterMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	Revelio(ctx context.Context, in *RevelioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TilePosition], error)
	Bombarda(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TilePosition, Empty], error)
}

type labyrinthClient struct {
	cc grpc.ClientConnInterface
}

func NewLabyrinthClient(cc grpc.ClientConnInterface) LabyrinthClient {
	return &labyrinthClient{cc}
}

func (c *labyrinthClient) GetLabyrinthInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LabyrinthInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LabyrinthInfo)
	err := c.cc.Invoke(ctx, Labyrinth_GetLabyrinthInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labyrinthClient) GetPlayerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlayerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatus)
	err := c.cc.Invoke(ctx, Labyrinth_GetPlayerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labyrinthClient) RegisterMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, Labyrinth_RegisterMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labyrinthClient) Revelio(ctx context.Context, in *RevelioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TilePosition], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Labyrinth_ServiceDesc.Streams[0], Labyrinth_Revelio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RevelioRequest, TilePosition]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Labyrinth_RevelioClient = grpc.ServerStreamingClient[TilePosition]

func (c *labyrinthClient) Bombarda(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TilePosition, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Labyrinth_ServiceDesc.Streams[1], Labyrinth_Bombarda_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TilePosition, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Labyrinth_BombardaClient = grpc.ClientStreamingClient[TilePosition, Empty]

// LabyrinthServer is the server API for Labyrinth service.
// All implementations must embed UnimplementedLabyrinthServer
// for forward compatibility.
type LabyrinthServer interface {
	GetLabyrinthInfo(context.Context, *Empty) (*LabyrinthInfo, error)
	GetPlayerStatus(context.Context, *Empty) (*PlayerStatus, error)
	RegisterMove(context.Context, *MoveRequest) (*MoveResponse, error)
	Revelio(*RevelioRequest, grpc.ServerStreamingServer[TilePosition]) error
	Bombarda(grpc.ClientStreamingServer[TilePosition, Empty]) error
	mustEmbedUnimplementedLabyrinthServer()
}

// UnimplementedLabyrinthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLabyrinthServer struct{}

func (UnimplementedLabyrinthServer) GetLabyrinthInfo(context.Context, *Empty) (*LabyrinthInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabyrinthInfo not implemented")
}
func (UnimplementedLabyrinthServer) GetPlayerStatus(context.Context, *Empty) (*PlayerStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStatus not implemented")
}
func (UnimplementedLabyrinthServer) RegisterMove(context.Context, *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMove not implemented")
}
func (UnimplementedLabyrinthServer) Revelio(*RevelioRequest, grpc.ServerStreamingServer[TilePosition]) error {
	return status.Errorf(codes.Unimplemented, "method Revelio not implemented")
}
func (UnimplementedLabyrinthServer) Bombarda(grpc.ClientStreamingServer[TilePosition, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Bombarda not implemented")
}
func (UnimplementedLabyrinthServer) mustEmbedUnimplementedLabyrinthServer() {}
func (UnimplementedLabyrinthServer) testEmbeddedByValue()                   {}

// UnsafeLabyrinthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabyrinthServer will
// result in compilation errors.
type UnsafeLabyrinthServer interface {
	mustEmbedUnimplementedLabyrinthServer()
}

func RegisterLabyrinthServer(s grpc.ServiceRegistrar, srv LabyrinthServer) {
	// If the following call pancis, it indicates UnimplementedLabyrinthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Labyrinth_ServiceDesc, srv)
}

func _Labyrinth_GetLabyrinthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabyrinthServer).GetLabyrinthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labyrinth_GetLabyrinthInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabyrinthServer).GetLabyrinthInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labyrinth_GetPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabyrinthServer).GetPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labyrinth_GetPlayerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabyrinthServer).GetPlayerStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labyrinth_RegisterMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabyrinthServer).RegisterMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Labyrinth_RegisterMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabyrinthServer).RegisterMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Labyrinth_Revelio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RevelioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LabyrinthServer).Revelio(m, &grpc.GenericServerStream[RevelioRequest, TilePosition]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Labyrinth_RevelioServer = grpc.ServerStreamingServer[TilePosition]

func _Labyrinth_Bombarda_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LabyrinthServer).Bombarda(&grpc.GenericServerStream[TilePosition, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Labyrinth_BombardaServer = grpc.ClientStreamingServer[TilePosition, Empty]

// Labyrinth_ServiceDesc is the grpc.ServiceDesc for Labyrinth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Labyrinth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "labyrinth.Labyrinth",
	HandlerType: (*LabyrinthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLabyrinthInfo",
			Handler:    _Labyrinth_GetLabyrinthInfo_Handler,
		},
		{
			MethodName: "GetPlayerStatus",
			Handler:    _Labyrinth_GetPlayerStatus_Handler,
		},
		{
			MethodName: "RegisterMove",
			Handler:    _Labyrinth_RegisterMove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Revelio",
			Handler:       _Labyrinth_Revelio_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Bombarda",
			Handler:       _Labyrinth_Bombarda_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "labyrinth.proto",
}
